name: Python CI - Online Bookstore

on:
  push:
    branches: [ "main", "testing-branch" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2 - Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'   # safer and faster for Actions runners

      # Step 3 - Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest pytest-cov flask

      # Step 4 - Run all tests from the tests folder
      - name: Run tests with Pytest
        run: |
          pytest tests/ -v --maxfail=5 --disable-warnings --cache-clear --cov=.

      # Step 5 - Upload test results (optional)
      - name: Upload pytest results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: .pytest_cache/
