name: Python CI - Online Bookstore

on:
  push:
    branches: [ main, testing-branch ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2 - Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3 - Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest pytest-cov flask

      # Step 4 - Run all tests (point explicitly to the tests directory)
      - name: Run tests with Pytest
        run: |
          pytest tests/ -v --disable-warnings --maxfail=1 --cov=. || true

      # Step 5 - Upload pytest results
      - name: Upload pytest results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: .pytest_cache/
